---
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo

  vars_files:
  - ./templates/loadbalancer.yml

  roles: 
  - role: apache-centos
    when: ansible_facts ['os_family'] == "RedHat"
  - role: apache-debian
    when: ansible_facts ['os_family'] == "Debian" 

  tasks:


#Puertos abiertos 80 y 443
  - name: Puertos abiertos
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
    - https
    - http

#Balance carga
  - name: Create loadbalancer configuration
    template:
      src: templates/loadbalancer.j2
      dest: /etc/httpd/vhost.d/loadbalancer.conf
      owner: root
      mode: 0644
    when: ansible_facts['os_family'] == "RedHat"
    notify: Restart httpd
    
  - name: Create loadbalancer configuration
    template:
      src: templates/apache2.j2
      dest: /etc/apache2/sites-enabled/000-default.conf
      owner: root
      mode: 0644
    when: ansible_facts['os_family'] == "Debian"
    notify: Restart apache2


